-- CATEGORY
INSERT INTO category VALUES (1, 'Alimentos');
INSERT INTO category VALUES (2, 'Eletrodomésticos');
INSERT INTO category VALUES (3, 'Móveis');


-- PRODUCT;
INSERT INTO PRODUCT VALUES (1, 'Arroz', 1);
INSERT INTO PRODUCT VALUES (2, 'Feijão', 1);

INSERT INTO PRODUCT VALUES (3, 'Aspirador de pó', 2);
INSERT INTO PRODUCT VALUES (4, 'Batedeira', 2);
INSERT INTO PRODUCT VALUES (5, 'Liquidificador', 2);

INSERT INTO PRODUCT VALUES (6, 'Sofá', 3);
INSERT INTO PRODUCT VALUES (7, 'Mesa', 3);
INSERT INTO PRODUCT VALUES (8, 'Estante', 3);